=== morkandmindy/Adventure/Adventure/GameData.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Directions" type="Directions" />
  <xs:simpleType name="Directions">
    <xs:restriction base="xs:string">
      <xs:enumeration value="North" />
      <xs:enumeration value="South" />
      <xs:enumeration value="East" />
      <xs:enumeration value="West" />
      <xs:enumeration value="Up" />
      <xs:enumeration value="Down" />
      <xs:enumeration value="NorthEast" />
      <xs:enumeration value="NorthWest" />
      <xs:enumeration value="SouthEast" />
      <xs:enumeration value="SouthWest" />
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="Door" nillable="true" type="Door" />
  <xs:complexType name="Door">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="WorkingKeys" type="Key" />
      <xs:element minOccurs="0" maxOccurs="1" name="LongDescription" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="ShortDescription" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="Key">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="1" name="LongDescription" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="ShortDescription" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
  <xs:element name="Game" nillable="true" type="Game" />
  <xs:complexType name="Game">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="1" name="Rooms" type="ArrayOfRoom" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ArrayOfRoom">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Room" nillable="true" type="Room" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="Room">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="1" name="Passages" type="ArrayOfPassage" />
    </xs:sequence>
    <xs:attribute name="Id" type="xs:int" use="required" />
    <xs:attribute name="LongDescription" type="xs:string" />
    <xs:attribute name="ShortDescription" type="xs:string" />
  </xs:complexType>
  <xs:complexType name="ArrayOfPassage">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Passage" nillable="true" type="Passage" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="Passage">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="1" name="Door" type="Door" />
    </xs:sequence>
    <xs:attribute name="Direction" type="Directions" use="required" />
    <xs:attribute name="Destination" type="xs:int" use="required" />
    <xs:attribute name="LongDescription" type="xs:string" />
    <xs:attribute name="ShortDescription" type="xs:string" />
  </xs:complexType>
  <xs:element name="Key" nillable="true" type="Key" />
  <xs:element name="Passage" nillable="true" type="Passage" />
  <xs:element name="Room" nillable="true" type="Room" />
</xs:schema>

=== morkandmindy/Adventure/Adventure/GameData.xml
<?xml version="1.0" ?>
<Game xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:xsd="http://www.w3.org/2001/XmlSchema"
  xsi:schemaLocation="urn:GameData GameData.xsd">
  <Rooms>
    <Room LongDescription="You are in a big cavern. There are passages leading to the north and east." Id="1">
      <Passages>
        <Passage Direction="North" Destination="2" />
        <Passage Direction="East" Destination="3" />
      </Passages>
    </Room>
    <Room LongDescription="You are in a small cave with water dripping from the ceiling. There is a passage leading south and a difficult crawl down a pit." Id="2">
      <Passages>
        <Passage Direction="South" Destination="1" />
        <Passage Direction="Down" Destination="5" />
      </Passages>
    </Room>
    <Room LongDescription="You are in a long hallway stretching to the east and west." Id="3" >
      <Passages>
        <Passage Direction="West" Destination="1" />
        <Passage Direction="East" Destination="4" />
      </Passages>
    </Room>
    <Room LongDescription="You are in a beautifully carved chamber whose walls are solid marble. There is an exit to the west." Id="4" >
      <Passages>
        <Passage Direction="West" Destination="3" />
      </Passages>
    </Room>
    <Room LongDescription="You are at the bottom of a damp pit. The only way out is up." Id="5" >
      <Passages>
        <Passage Direction="Up" Destination="2" />
      </Passages>
    </Room>
  </Rooms>
</Game>
